name: Cut Final Release
description: Cut Final Release of packages

inputs:
  action:
    description: "The main action to perform: cut, bump, or both"
    required: true
  base-ref:
    description: "Base ref to use for the release"
    required: false

# outputs:
#   image-name:
#     value: ${{ steps.build-image.outputs.image-name }}

runs:
  using: "node16"
  main: "dist/index.js"

branding:
  icon: "package"
  color: "blue"
