name: 'Run something'
description: 'Try to run something'

inputs:
  image:
    required: true
    type: string
  site-url:
    required: true
    type: string
  publish:
    required: false

runs:
  using: "composite"
  steps:
    - shell: bash
      name: Github Info
      run: |
        echo "GITHUB_ACTION: $GITHUB_ACTION"
        echo "GITHUB_ACTOR: $GITHUB_ACTOR"
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
        echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
        echo "github.event_name: ${{ github.event_name }}"
        cat $GITHUB_EVENT_PATH
        echo "full_name: ${{ github.event.pull_request.head.repo.full_name }}"
        echo "github.repository: ${{ github.repository }}"

    - shell: bash
      run: |
        echo "Hello World"

        ls -l /tmp/docker-cache

        cat /tmp/feito

    - run: |
        LOWERCASE_REPOSITORY=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")

        IMAGE_TAG="pr-${{ github.event.number }}"

        # TODO this needs to be different on develop and on release
        IMAGE_NAME="ghcr.io/${LOWERCASE_REPOSITORY}/rocket.chat:${IMAGE_TAG}"

        echo "IMAGE_NAME: ${IMAGE_NAME}"

        sleep 10

        echo "done"
      shell: bash

    - shell: bash
      run: |
        echo "GOING TO PUSH THOSE IMAGES >${{ inputs.publish }}<"

    - shell: bash
      if: github.event.pull_request.head.repo.full_name == github.repository
      run: |
        echo "Can make IF here as well"

