on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

    - name: Get GitHub Pages Data
      uses: actions/github-script@v3
      id: pages-data
      with:
        script: |
          const result = await github.request('GET /repos/{owner}/{repo}/pages', {
            owner: context.repo.owner,
            repo: context.repo.repo
          })
          return result.data

    - name: Checkout PR branch
      uses: actions/checkout@v2
      with:
        ref: refs/heads/${{ fromJSON(steps.pages-data.outputs.result).source.branch }}

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ github.event.workflow_run.name }}
        run_id: ${{ github.event.workflow_run.id }}
        name: build
        path: /tmp/build

    - name: Unpack build
      run: |
        cd /tmp/build
        ls -l

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - name: Unpack build
      run: |
        echo "did not work"
