name: New release

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Release type
        default: minor
        required: true
        options:
        - major
        - minor
        - patch
      base-ref:
        description: Base version
        default: master
        required: true

jobs:
  new-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
      # with:
      #   ref: ${{ github.event.inputs.base-ref }}

    # - run: yarn install

    - run: npm i -g @rocket.chat/houston@next

    - run: houston create-branch -t ${{ github.event.inputs.name }} -b ${{ github.event.inputs.base-ref }}

    - run: |
        git status

        git branch

        git push --set-upstream origin release-3.1.0
