name: Start new release

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Release type
        default: next
        required: true
        options:
        - next
        - patch
      base-ref:
        description: Base version
        default: master
        required: false

jobs:
  new-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
      # with:
      #   ref: ${{ github.event.inputs.base-ref }}

    - run: npm install

    # - run: npm i -g @rocket.chat/houston@next

    # - run: houston create-branch -t ${{ github.event.inputs.name }} -b ${{ github.event.inputs.base-ref }}

    - name: Create Pull Request if next
      if: ${{ github.event.inputs.name == 'next' }}
      run: |
        node .scripts/bumpNextVersion.js
