name: Start new release

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Release type
        default: next
        required: true
        options:
        - next
        - patch
      base-ref:
        description: Base version
        default: master
        required: false

jobs:
  new-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
      # with:
      #   ref: ${{ github.event.inputs.base-ref }}

    - name: Setup Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - run: yarn install

    # - run: npm i -g @rocket.chat/houston@next

    # - run: houston create-branch -t ${{ github.event.inputs.name }} -b ${{ github.event.inputs.base-ref }}

    - name: Authenticate with private NPM package
      if: ${{ github.event.inputs.name == 'next' }}
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

    - name: Create Pull Request if next
      if: ${{ github.event.inputs.name == 'next' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        yarn node .scripts/bumpNextVersion.js
