name: CI

on:
  release:
    types: [published]
  pull_request:
    branches: '**'
  push:
    branches:
      - master

jobs:
  docker-tags:
    runs-on: ubuntu-latest
    outputs:
      docker-tag: ${{ steps.step1.outputs.docker-tag }}
      release: ${{ steps.step1.outputs.release }}
      latest-release: ${{ steps.step1.outputs.latest-release }}
    steps:
      - id: step1
        run: |
          DOCKER_TAG=$GITHUB_REF_NAME

          if echo "$GITHUB_REF_NAME" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' ; then
            RELEASE="latest"
          elif echo "$GITHUB_REF_NAME" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+$' ; then
            RELEASE="release-candidate"
          fi

          LATEST_RELEASE="$(
            git -c 'versionsort.suffix=-' ls-remote -t --exit-code --refs --sort=-v:refname "https://github.com/$GITHUB_REPOSITORY" '*' |
              sed -En '1!q;s/^[[:xdigit:]]+[[:space:]]+refs\/tags\/(.+)/\1/gp'
          )"

          echo "DOCKER_TAG: $DOCKER_TAG"
          echo "RELEASE: $RELEASE"
          echo "LATEST_RELEASE: $LATEST_RELEASE"

          echo "::set-output name=docker-tag::${DOCKER_TAG}"
          echo "::set-output name=release::${RELEASE}"
          echo "::set-output name=latest-release::${LATEST_RELEASE}"

  build:

    runs-on: ubuntu-latest

    steps:
    - shell: bash
      name: Github Info
      run: |
        echo "GITHUB_ACTION: $GITHUB_ACTION"
        echo "GITHUB_ACTOR: $GITHUB_ACTOR"
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
        echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
        echo "github.event_name: ${{ github.event_name }}"
        cat $GITHUB_EVENT_PATH
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  image-build:
    runs-on: ubuntu-latest
    needs: [build, docker-tags]

    steps:
      - uses: actions/checkout@v2

      # -
      #   name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ secrets.CR_USER }}
      #     password: ${{ secrets.CR_PAT }}

      - name: Unpack build
        run: |

      - name: Build Docker image for PRs
        run: |
          echo "WTF1 ${{needs.docker-tags.outputs.docker-tag}}"
          echo "WTF2 ${{needs.docker-tags.outputs.release}}"
          echo "WTF3 ${{needs.docker-tags.outputs.latest-release}}"

          LOWERCASE_REPOSITORY=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IMAGE_NAME="actions-playground"

          IMAGE_NAME="ghcr.io/${LOWERCASE_REPOSITORY}/${IMAGE_NAME}:pr-2${{ github.event.number }}"
          # IMAGE_NAME="${IMAGE_NAME}:pr-2${{ github.event.number }}"

          echo "Build official Docker image ${IMAGE_NAME}"

          # mkdir /tmp/docker-cache

          docker build -t $IMAGE_NAME .

          docker images

          mkdir /tmp/docker-cache
          docker save "$IMAGE_NAME" > /tmp/docker-cache/docker-image.tar

          ls -l /tmp/docker-cache

      - uses: actions/upload-artifact@v2
        with:
          name: docker-artifact
          path: /tmp/docker-cache

  image-usage:
    runs-on: ubuntu-latest
    needs: [image-build]
    steps:
      - uses: actions/checkout@v2

      - name: Download Docker Image (Artifact)
        uses: actions/download-artifact@v2
        with:
          name: docker-artifact
          path: /tmp/docker-cache

      - name: Run test in Docker
        run: |
          cd /tmp/docker-cache
          docker load < docker-image.tar

          echo "ok" > /tmp/feito

      - uses: ./.github/actions/run-something
        with:
          image: 'some image'
          site-url: 'idk site url'
          publish: github.event.pull_request.head.repo.full_name == github.repository

      - name: Use image
        run: |
          LOWERCASE_REPOSITORY=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
          IMAGE_NAME="actions-playground"

          IMAGE_NAME="ghcr.io/${LOWERCASE_REPOSITORY}/${IMAGE_NAME}:pr-2${{ github.event.number }}"

          docker images

          echo "IMAGE_NAME: ${IMAGE_NAME}"

          # docker run $IMAGE_NAME
