name: 'Release PR Description'

on:
  pull_request:
    branches:
      - 'release-*'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  update-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Update PR description
        uses: ./packages/release-action
        with:
          action: update-pr-description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

